version: '3.8'

services:
  paypos-fe:
    container_name: paypos-fe
    build:
      context: .
      target: builder
    ports:
      - "8081:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
      - VITE_API_URL=paypos-service:8080